export const DEFAULT_DB_SCHEMA: Record<string, string[]> = {
  inducks_story: [
    "storycode",
    "title",
    "kind",
    "pages",
    "languagecode",
    "countrycode",
    "firstpublicationdate",
    "publisherid",
    "seriescode",
    "uscp",
    "comment",
  ],
  inducks_issue: [
    "issuecode",
    "publicationcode",
    "year",
    "month",
    "day",
    "pages",
    "languagecode",
    "countrycode",
    "editor",
    "isbn",
  ],
  inducks_publication: [
    "publicationcode",
    "publicationname",
    "publisherid",
    "countrycode",
    "languagecode",
    "year",
    "month",
    "type",
  ],
  inducks_author: [
    "personcode",
    "fullname",
    "countrycode",
    "birthyear",
    "deathyear",
    "gender",
  ],
  inducks_character: [
    "charactercode",
    "charactername",
    "firstappearance",
    "countrycode",
  ],
  inducks_publisher: [
    "publisherid",
    "publishername",
    "countrycode",
    "languagecode",
  ],
  inducks_series: [
    "seriescode",
    "seriesname",
    "publisherid",
    "countrycode",
    "languagecode",
  ],
  inducks_storyauthor: ["storycode", "personcode", "role"],
  inducks_storycharacter: ["storycode", "charactercode", "role"],
  inducks_seriesstory: ["seriescode", "storycode", "sequence"],
}
