export const DEFAULT_DB_SCHEMA: Record<string, string[]> = {
  inducks_appearance: [
    "storyversioncode",
    "charactercode",
    "number",
    "appearancecomment",
    "doubt",
  ],
  inducks_character: [
    "charactercode",
    "charactername",
    "official",
    "onetime",
    "heroonly",
    "charactercomment",
  ],
  inducks_characteralias: [
    "charactercode",
    "charactername",
  ],
  inducks_characterdetail: [
    "charactername",
    "charactercode",
    "number",
  ],
  inducks_charactername: [
    "charactercode",
    "languagecode",
    "charactername",
    "preferred",
    "characternamecomment",
  ],
  inducks_characterreference: [
    "fromcharactercode",
    "tocharactercode",
    "isgroupofcharacters",
  ],
  inducks_characterurl: [
    "charactercode",
    "sitecode",
    "url",
  ],
  inducks_country: [
    "countrycode",
    "countryname",
    "defaultlanguage",
    "defaultmaintenanceteam",
  ],
  inducks_countryname: [
    "countrycode",
    "languagecode",
    "countryname",
  ],
  inducks_currency: [
    "currencycode",
    "currencyname",
  ],
  inducks_currencyname: [
    "currencycode",
    "languagecode",
    "shortcurrencyname",
    "longcurrencyname",
  ],
  inducks_entry: [
    "entrycode",
    "issuecode",
    "storyversioncode",
    "languagecode",
    "includedinentrycode",
    "position",
    "printedcode",
    "guessedcode",
    "title",
    "reallytitle",
    "printedhero",
    "changes",
    "cut",
    "minorchanges",
    "missingpanels",
    "mirrored",
    "sideways",
    "startdate",
    "enddate",
    "identificationuncertain",
    "alsoreprint",
    "part",
    "entrycomment",
    "error",
  ],
  inducks_entrycharactername: [
    "entrycode",
    "charactercode",
    "charactername",
  ],
  inducks_entryjob: [
    "entrycode",
    "personcode",
    "transletcol",
    "entryjobcomment",
    "doubt",
  ],
  inducks_entryurl: [
    "entrycode",
    "sitecode",
    "pagenumber",
    "url",
    "storycode",
    "public",
  ],
  inducks_equiv: [
    "issuecode",
    "equivid",
    "equivcomment",
  ],
  inducks_herocharacter: [
    "storycode",
    "charactercode",
    "number",
    "doubt",
  ],
  inducks_inputfile: [
    "inputfilecode",
    "path",
    "filename",
    "layout",
    "locked",
    "maintenanceteamcode",
    "countrycode",
    "languagecode",
    "producercode",
    "secundary",
  ],
  inducks_issue: [
    "issuecode",
    "issuerangecode",
    "publicationcode",
    "issuenumber",
    "title",
    "size",
    "pages",
    "price",
    "printrun",
    "attached",
    "oldestdate",
    "fullyindexed",
    "issuecomment",
    "error",
    "filledoldestdate",
    "locked",
    "inxforbidden",
    "inputfilecode",
    "maintenanceteamcode",
  ],
  inducks_issuecollecting: [
    "collectingissuecode",
    "collectedissuecode",
  ],
  inducks_issuedate: [
    "issuecode",
    "date",
    "kindofdate",
    "doubt",
  ],
  inducks_issuejob: [
    "issuecode",
    "personcode",
    "inxtransletcol",
    "issuejobcomment",
    "doubt",
  ],
  inducks_issueprice: [
    "issuecode",
    "amount",
    "currency",
    "comment",
    "sequencenumber",
  ],
  inducks_issuerange: [
    "issuerangecode",
    "publicationcode",
    "title",
    "circulation",
    "issuerangecomment",
    "numbersarefake",
    "error",
  ],
  inducks_issueurl: [
    "issuecode",
    "sitecode",
    "url",
  ],
  inducks_language: [
    "languagecode",
    "defaultlanguagecode",
    "languagename",
  ],
  inducks_languagename: [
    "desclanguagecode",
    "languagecode",
    "languagename",
  ],
  inducks_log: [
    "number",
    "logkey",
    "storycode",
    "logid",
    "logtype",
    "par1",
    "par2",
    "par3",
    "marked",
    "inputfilecode",
    "maintenanceteamcode",
  ],
  inducks_logdata: [
    "logid",
    "category",
    "logtext",
  ],
  inducks_logocharacter: [
    "entrycode",
    "charactercode",
    "reallyintitle",
    "number",
    "logocharactercomment",
  ],
  inducks_movie: [
    "moviecode",
    "title",
    "moviecomment",
    "appsummary",
    "moviejobsummary",
    "locked",
    "inputfilecode",
    "maintenanceteamcode",
    "appisxapp",
    "aka",
    "creationdate",
    "moviedescription",
    "distributor",
    "genre",
    "orderer",
    "publicationdate",
    "source",
    "tim",
  ],
  inducks_moviecharacter: [
    "moviecode",
    "charactercode",
    "istitlecharacter",
  ],
  inducks_moviejob: [
    "moviecode",
    "personcode",
    "role",
    "moviejobcomment",
    "indirect",
    "doubt",
  ],
  inducks_moviereference: [
    "storycode",
    "moviecode",
    "referencereasonid",
    "frommovietostory",
  ],
  inducks_person: [
    "personcode",
    "nationalitycountrycode",
    "fullname",
    "official",
    "personcomment",
    "unknownstudiomember",
    "isfake",
    "numberofindexedissues",
    "birthname",
    "borndate",
    "bornplace",
    "deceaseddate",
    "deceasedplace",
    "education",
    "moviestext",
    "comicstext",
    "othertext",
    "photofilename",
    "photocomment",
    "photosource",
    "personrefs",
  ],
  inducks_personalias: [
    "personcode",
    "surname",
    "givenname",
    "official",
  ],
  inducks_personurl: [
    "personcode",
    "sitecode",
    "url",
  ],
  inducks_publication: [
    "publicationcode",
    "countrycode",
    "languagecode",
    "title",
    "size",
    "publicationcomment",
    "circulation",
    "numbersarefake",
    "error",
    "locked",
    "inxforbidden",
    "inputfilecode",
    "maintenanceteamcode",
  ],
  inducks_publicationcategory: [
    "publicationcode",
    "category",
  ],
  inducks_publicationname: [
    "publicationcode",
    "publicationname",
  ],
  inducks_publicationurl: [
    "publicationcode",
    "sitecode",
    "url",
  ],
  inducks_publisher: [
    "publisherid",
    "publishername",
  ],
  inducks_publishingjob: [
    "publisherid",
    "issuecode",
    "publishingjobcomment",
  ],
  inducks_referencereason: [
    "referencereasonid",
    "referencereasontext",
  ],
  inducks_referencereasonname: [
    "referencereasonid",
    "languagecode",
    "referencereasontranslation",
  ],
  inducks_site: [
    "sitecode",
    "urlbase",
    "images",
    "sitename",
    "sitelogo",
    "properties",
  ],
  inducks_statcharactercharacter: [
    "charactercode",
    "cocharactercode",
    "total",
    "yearrange",
  ],
  inducks_statcharactercountry: [
    "charactercode",
    "countrycode",
    "total",
  ],
  inducks_statcharacterstory: [
    "charactercode",
    "storyheadercode",
    "total",
    "yearrange",
  ],
  inducks_statpersoncharacter: [
    "personcode",
    "charactercode",
    "total",
    "yearrange",
  ],
  inducks_statpersoncountry: [
    "personcode",
    "countrycode",
    "total",
  ],
  inducks_statpersonperson: [
    "personcode",
    "copersoncode",
    "total",
    "yearrange",
  ],
  inducks_statpersonstory: [
    "personcode",
    "storyheadercode",
    "total",
    "yearrange",
  ],
  inducks_story: [
    "storycode",
    "originalstoryversioncode",
    "firstpublicationdate",
    "endpublicationdate",
    "title",
    "usedifferentcode",
    "storycomment",
    "error",
    "repcountrysummary",
    "storyparts",
    "locked",
    "inputfilecode",
    "issuecodeofstoryitem",
    "maintenanceteamcode",
    "storyheadercode",
  ],
  inducks_storycodes: [
    "storycode",
    "alternativecode",
    "unpackedcode",
    "codecomment",
  ],
  inducks_storycreationdate: [
    "storycode",
    "creationdate",
    "creationcomment",
  ],
  inducks_storydescription: [
    "storyversioncode",
    "languagecode",
    "desctext",
  ],
  inducks_storyheader: [
    "storyheadercode",
    "level",
    "title",
    "storyheadercomment",
    "countrycode",
  ],
  inducks_storyjob: [
    "storyversioncode",
    "personcode",
    "plotwritartink",
    "storyjobcomment",
    "indirect",
    "doubt",
  ],
  inducks_storyreference: [
    "fromstorycode",
    "tostorycode",
    "referencereasonid",
  ],
  inducks_storysubseries: [
    "storycode",
    "subseriescode",
    "storysubseriescomment",
  ],
  inducks_storyurl: [
    "storycode",
    "sitecode",
    "url",
  ],
  inducks_storyversion: [
    "storyversioncode",
    "storycode",
    "entirepages",
    "brokenpagenumerator",
    "brokenpagedenominator",
    "brokenpageunspecified",
    "kind",
    "rowsperpage",
    "columnsperpage",
    "appisxapp",
    "what",
    "appsummary",
    "plotsummary",
    "writsummary",
    "artsummary",
    "inksummary",
    "creatorrefsummary",
    "keywordsummary",
    "estimatedpanels",
  ],
  inducks_studio: [
    "studiocode",
    "countrycode",
    "studioname",
    "city",
    "description",
    "othertext",
    "photofilename",
    "photocomment",
    "photosource",
    "studiorefs",
  ],
  inducks_studiowork: [
    "studiocode",
    "personcode",
  ],
  inducks_subseries: [
    "subseriescode",
    "subseriesname",
    "official",
    "subseriescomment",
    "subseriescategory",
  ],
  inducks_subseriesname: [
    "subseriescode",
    "languagecode",
    "subseriesname",
    "preferred",
    "subseriesnamecomment",
  ],
  inducks_substory: [
    "storycode",
    "originalstoryversioncode",
    "superstorycode",
    "part",
    "firstpublicationdate",
    "title",
    "substorycomment",
    "error",
    "locked",
    "inputfilecode",
    "maintenanceteamcode",
  ],
  inducks_team: [
    "teamcode",
    "teamdescriptionname",
    "teamshortname",
  ],
  inducks_teammember: [
    "teamcode",
    "personcode",
  ],
  inducks_ucrelation: [
    "universecode",
    "charactercode",
  ],
  inducks_universe: [
    "universecode",
    "universecomment",
  ],
  inducks_universename: [
    "universecode",
    "languagecode",
    "universename",
  ],
};
